name: 'setup-netrc'
description: 'Setup .netrc file'
author: 'Conventional Actions'
inputs:
  machine:
    description: 'The remote machine name'
    required: false
    default: 'github.com'
  username:
    description: 'The remote username'
    required: false
    default: '' # GITHUB_REPOSITORY_OWNER
  password:
    description: 'The remote password'
    required: false
    default: '' # GITHUB_TOKEN
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  color: "purple"
  icon: "radio"
